version: '3.8'

networks:
  default:

services:
  db1:
    image: mysql:5.7
    container_name: db1
    ports:
      - 3310:3306
    volumes:
      - "./.data/db/mysql1:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: toor1
      MYSQL_DATABASE: db1
  db2:
      image: mysql:5.7
      container_name: db2
      ports:
        - 3311:3306
      volumes:
        - "./.data/db/mysql2:/var/lib/mysql"
      environment:
        MYSQL_ROOT_PASSWORD: toor2
        MYSQL_DATABASE: db2
