version: '3.8'

networks:
  default:

services:
  db1:
    image: mysql:5.7
    container_name: db1
    ports:
      - "3310:3306"
    volumes:
      - "./.data/db/mysql1:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: toor1
      MYSQL_DATABASE: db1
  db2:
      image: postgres:14.4-alpine
      container_name: db2
      ports:
        - "3311:5432"
      volumes:
        - "./.data/db/postgres:/var/lib/postgresql/data"
      environment:
        POSTGRES_PASSWORD: toor2
        POSTGRES_DB: db2
