server:
  port: 9080

db1:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3310/db1
    username: root
    password: toor1

db2:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3311/db2
    username: root
    password: toor2

logging:
  level:
    com.demo: DEBUG
