server:
  port: 9080

db1:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3310/db1
    username: root
    password: toor1

db2:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
      javax:
        persistence:
          schema-generation:
            create-database-schemas: true
    hibernate:
      ddl-auto: create
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:3311/db2?currentSchema=db2
    username: postgres
    password: toor2

logging:
  level:
    com.demo: DEBUG
